influx:
  url: http://influxdb:8086
  token: Q-fBkm2C3LCg3f1kXv2r1b2YegeoN0-dJHiaBMrRkh55Te_Cq91SDWOPfu4wI7hOnS2j_rIYbTs8s-YP_IXf3g==
  org: stock-alert
  bucket: stock-alert
logging:
  level:
    root: info
    web: info